import { jsPDF } from "jspdf";
import { DashboardYearData, Year } from "@/data/mock";

/**
 * Utility function to generate and download a professional Dashboard PDF report using jsPDF.
 */
export function exportDashboardPDF(selectedYear: Year, data: DashboardYearData) {
  try {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 14;
    let y = 0;

    // Helper for page numbering and footer on every page
    const addHeaderAndFooter = () => {
      const pageCount = (doc.internal as any).getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);

        // Header line for pages > 1
        if (i > 1) {
          doc.setFont("helvetica", "normal");
          doc.setFontSize(8);
          doc.setTextColor(100, 116, 139);
          doc.text(`IndiaLens AI Dashboard Report – ${selectedYear}`, margin, 10);
          doc.setDrawColor(226, 232, 240);
          doc.line(margin, 12, pageWidth - margin, 12);
        }

        // Footer line & text on every page
        doc.setDrawColor(226, 232, 240);
        doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139);
        // Requirement 3: Footer must say "Generated by IndiaLens AI"
        doc.text("Generated by IndiaLens AI", margin, pageHeight - 6);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 18, pageHeight - 6);
      }
    };

    const checkOverflow = (neededHeight: number) => {
      if (y + neededHeight > pageHeight - 16) {
        doc.addPage();
        y = 18;
      }
    };

    // 1. Top Header Banner
    doc.setFillColor(15, 23, 42); // Dark slate navy
    doc.rect(0, 0, pageWidth, 28, "F");

    // Title / Brand Logo Text
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("IndiaLens AI", margin, 12);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(203, 213, 225);
    doc.text(`Dashboard Report – ${selectedYear}`, margin, 19);

    // Selected Year & Timestamp right-aligned
    const exportTimestamp = new Date().toLocaleString("en-US", {
      dateStyle: "medium",
      timeStyle: "short",
    });

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(255, 255, 255);
    doc.text(`Edition: ${selectedYear}`, pageWidth - margin - 35, 12);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(203, 213, 225);
    doc.text(`Exported: ${exportTimestamp}`, pageWidth - margin - 45, 19);

    y = 34;

    // Report Main Title
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(`IndiaLens AI Dashboard Report – ${selectedYear}`, margin, y);
    y += 7;

    // Calculate Overall Global Score
    const overallScoreNum =
      data.categories && data.categories.length > 0
        ? (
            data.categories.reduce((sum, cat) => sum + cat.overallScore, 0) /
            data.categories.length
          ).toFixed(1)
        : "N/A";

    // 2. Executive Summary & Overall Global Score Card
    doc.setFillColor(241, 245, 249);
    doc.setDrawColor(203, 213, 225);
    doc.roundedRect(margin, y, pageWidth - margin * 2, 28, 2, 2, "FD");

    // Overall Global Score Badge
    doc.setFillColor(30, 58, 138);
    doc.roundedRect(margin + 3, y + 3, 46, 22, 1.5, 1.5, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.text("OVERALL GLOBAL SCORE", margin + 5, y + 8);
    doc.setFontSize(13);
    doc.text(`${overallScoreNum} / 100`, margin + 5, y + 15.5);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.text("10 Strategic Domains Avg", margin + 5, y + 20.5);

    // Executive Summary Text
    doc.setTextColor(30, 41, 59);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text("Executive Summary", margin + 53, y + 8);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    const summaryLines = doc.splitTextToSize(
      data.aiSummary?.description || "Comprehensive analysis of India's global indicators.",
      pageWidth - margin * 2 - 57
    );
    doc.text(summaryLines, margin + 53, y + 13);

    y += 34;

    // 3. KPI Summary Section
    checkOverflow(40);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text("Key Performance Indicators Summary", margin, y);
    y += 5;

    // Table Header
    doc.setFillColor(226, 232, 240);
    doc.rect(margin, y, pageWidth - margin * 2, 6, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 41, 59);
    doc.text("Indicator", margin + 3, y + 4.5);
    doc.text("Global Rank", margin + 60, y + 4.5);
    doc.text("Score / Metric", margin + 95, y + 4.5);
    doc.text("Trend", margin + 140, y + 4.5);
    doc.text("Data Source", margin + 165, y + 4.5);
    y += 7;

    // Table Rows (KPI Summary: GDP, HDI, Innovation, Happiness, AI Readiness, Press Freedom, Global Peace, Gender Gap)
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);

    if (data.kpis && data.kpis.length > 0) {
      data.kpis.forEach((kpi) => {
        checkOverflow(7);
        doc.setTextColor(15, 23, 42);
        doc.setFont("helvetica", "bold");
        doc.text(kpi.title, margin + 3, y + 4.5);

        doc.setFont("helvetica", "bold");
        doc.setTextColor(30, 58, 138);
        doc.text(kpi.rank, margin + 60, y + 4.5);

        doc.setFont("helvetica", "normal");
        doc.setTextColor(51, 65, 85);
        doc.text(kpi.score, margin + 95, y + 4.5);

        doc.text(kpi.trend, margin + 140, y + 4.5);
        doc.text(kpi.source, margin + 165, y + 4.5);

        doc.setDrawColor(241, 245, 249);
        doc.line(margin, y + 6, pageWidth - margin, y + 6);
        y += 6.5;
      });
    }

    y += 6;

    // 4. Category Performance Overview Section
    checkOverflow(40);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text("Category Performance Overview", margin, y);
    y += 5;

    // Table Header
    doc.setFillColor(226, 232, 240);
    doc.rect(margin, y, pageWidth - margin * 2, 6, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 41, 59);
    doc.text("Category Domain", margin + 3, y + 4.5);
    doc.text("Overall Score", margin + 50, y + 4.5);
    doc.text("Global Rank", margin + 80, y + 4.5);
    doc.text("Strategic Description", margin + 110, y + 4.5);
    y += 7;

    // Table Rows
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);

    if (data.categories && data.categories.length > 0) {
      data.categories.forEach((cat) => {
        checkOverflow(8);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(15, 23, 42);
        doc.text(cat.name, margin + 3, y + 4.5);

        doc.setFont("helvetica", "normal");
        doc.setTextColor(30, 58, 138);
        doc.text(`${cat.overallScore.toFixed(1)} / 100`, margin + 50, y + 4.5);

        doc.setFont("helvetica", "bold");
        doc.setTextColor(15, 23, 42);
        doc.text(cat.globalRank, margin + 80, y + 4.5);

        doc.setFont("helvetica", "normal");
        doc.setTextColor(71, 85, 105);
        const descLine = doc.splitTextToSize(cat.description, pageWidth - margin - 110 - 3);
        doc.text(descLine[0] || "", margin + 110, y + 4.5);

        doc.setDrawColor(241, 245, 249);
        doc.line(margin, y + 6.5, pageWidth - margin, y + 6.5);
        y += 7;
      });
    }

    y += 6;

    // 5. AI Executive Insight & Recent Highlights Section
    if (data.aiSummary) {
      checkOverflow(35);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(15, 23, 42);
      doc.text("AI Executive Insight", margin, y);
      y += 5;

      doc.setFillColor(240, 253, 250);
      doc.setDrawColor(153, 246, 228);

      const insightText = `${data.aiSummary.title}: ${data.aiSummary.description}`;
      const insightLines = doc.splitTextToSize(insightText, pageWidth - margin * 2 - 8);
      const boxHeight = Math.max(14, insightLines.length * 3.8 + 6);
      checkOverflow(boxHeight + 10);

      doc.roundedRect(margin, y, pageWidth - margin * 2, boxHeight, 1.5, 1.5, "FD");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(15, 118, 110);
      doc.text(`[${data.aiSummary.badge}]`, margin + 4, y + 5);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(19, 78, 74);
      doc.text(insightLines, margin + 4, y + 9);

      y += boxHeight + 6;
    }

    if (data.highlights && data.highlights.length > 0) {
      checkOverflow(25);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      doc.text("Key Releases & Major Milestones:", margin, y);
      y += 4.5;

      data.highlights.forEach((h) => {
        checkOverflow(10);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        doc.setTextColor(30, 58, 138);
        doc.text(`• ${h.title} (${h.publisher} - ${h.date})`, margin + 3, y + 3.5);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(7.5);
        doc.setTextColor(71, 85, 105);
        const hLines = doc.splitTextToSize(
          `Rank/Badge: ${h.currentRank} [${h.changeBadge}] — ${h.description}`,
          pageWidth - margin * 2 - 8
        );
        doc.text(hLines, margin + 7, y + 7.5);
        y += hLines.length * 3.5 + 5;
      });
    }

    // Add page numbers and footer to all pages
    addHeaderAndFooter();

    // Save PDF file with exact name format required: IndiaLensAI_Dashboard_<selectedYear>.pdf
    doc.save(`IndiaLensAI_Dashboard_${selectedYear}.pdf`);
  } catch (error) {
    console.error("Failed to generate Dashboard PDF report:", error);
  }
}
