import { jsPDF } from "jspdf";
import { GeneratedReport } from "./report-data";

/**
 * Utility function to trigger a CSV download for any GeneratedReport
 */
export function exportReportCSV(report: GeneratedReport) {
  const lines: string[] = [];

  // Metadata
  lines.push(`"INDIALENS AI INTELLIGENCE REPORT"`);
  lines.push(`"Title","${report.title.replace(/"/g, '""')}"`);
  lines.push(`"Report Type","${report.type.toUpperCase()}"`);
  lines.push(`"Evaluation Year","${report.year}"`);
  lines.push(`"Benchmark Target","${report.benchmarkCountry}"`);
  lines.push(`"Generated Date","${report.generatedAt}"`);
  lines.push("");

  // Executive Summary
  lines.push(`"EXECUTIVE SUMMARY"`);
  lines.push(`"${report.executiveSummary.replace(/"/g, '""')}"`);
  lines.push("");

  // Key Strategic Indicators Table
  lines.push(`"KEY STRATEGIC INDICATORS"`);
  lines.push(`"Indicator","Category","Global Rank","Metric Score","Change","Status","Data Source"`);
  report.keyIndicators.forEach((ind) => {
    lines.push(
      `"${ind.name}","${ind.category}","${ind.globalRank}","${ind.score}","${ind.change}","${ind.status}","${ind.source}"`
    );
  });
  lines.push("");

  // Category Performance Table
  lines.push(`"CATEGORY PERFORMANCE BENCHMARKS"`);
  lines.push(`"Category","Overall Score (0-100)","Global Rank","Top Global Peer","Performance Gap","Status"`);
  report.categoryPerformance.forEach((cat) => {
    lines.push(
      `"${cat.name}","${cat.score}","${cat.globalRank}","${cat.topPeer}","${cat.gap}","${cat.status}"`
    );
  });
  lines.push("");

  // Historical Trends
  lines.push(`"HISTORICAL MULTI-YEAR TRAJECTORY"`);
  lines.push(`"Year","Rank / Index Score","Key Milestone"`);
  report.historicalTrends.forEach((t) => {
    lines.push(`"${t.year}","${t.score} (${t.rank})","${t.event.replace(/"/g, '""')}"`);
  });
  lines.push("");

  // Bilateral Comparison if applicable
  if (report.comparisonData) {
    lines.push(`"BILATERAL COMPARISON WITH ${report.benchmarkCountry.toUpperCase()}"`);
    lines.push(`"Indicator","Category","India Value","India Rank","${report.benchmarkCountry} Value","${report.benchmarkCountry} Rank","Leader"`);
    report.comparisonData.rows.forEach((row) => {
      lines.push(
        `"${row.indicator}","${row.category}","${row.indiaVal}","${row.indiaRank}","${row.peerVal}","${row.peerRank}","${row.leader}"`
      );
    });
    lines.push("");
  }

  // Strengths
  lines.push(`"KEY STRATEGIC STRENGTHS"`);
  report.strengths.forEach((str, i) => {
    lines.push(`"${i + 1}","${str.replace(/"/g, '""')}"`);
  });
  lines.push("");

  // Areas for Improvement
  lines.push(`"AREAS FOR POLICY IMPROVEMENT"`);
  report.areasForImprovement.forEach((area, i) => {
    lines.push(`"${i + 1}","${area.replace(/"/g, '""')}"`);
  });
  lines.push("");

  // AI Recommendations
  lines.push(`"AI EXECUTIVE RECOMMENDATIONS"`);
  report.aiRecommendations.forEach((rec, i) => {
    lines.push(`"${i + 1}","${rec.replace(/"/g, '""')}"`);
  });
  lines.push("");

  // Data Sources
  lines.push(`"DATA SOURCES & CITATIONS"`);
  report.dataSources.forEach((src) => {
    lines.push(`"${src.replace(/"/g, '""')}"`);
  });
  lines.push("");
  lines.push(`"Report generated by IndiaLens AI Platform - Confidential & Official Benchmark Data"`);

  const csvContent = lines.join("\n");
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute(
    "download",
    `IndiaLensAI_Report_${report.year}.csv`
  );
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Utility function to generate and download a professional PDF document using jsPDF
 */
export function exportReportPDF(report: GeneratedReport) {
  try {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    let y = 20;

    // Header Title Banner
    doc.setFillColor(30, 58, 138); // Deep Navy
    doc.rect(0, 0, pageWidth, 28, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("IndiaLens AI — Intelligence Report", margin, 14);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("Global Progress & International Benchmark Platform", margin, 21);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text(`YEAR: ${report.year}`, pageWidth - margin - 25, 14);
    doc.text(`DATE: ${report.generatedAt}`, pageWidth - margin - 35, 21);

    y = 36;

    // Report Title
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(report.title, margin, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(100, 116, 139);
    const subtitleLines = doc.splitTextToSize(report.subtitle, pageWidth - margin * 2);
    doc.text(subtitleLines, margin, y);
    y += subtitleLines.length * 4 + 4;

    // Metadata Bar
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.rect(margin, y, pageWidth - margin * 2, 10, "FD");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(30, 58, 138);
    doc.text(`TYPE: ${report.type.toUpperCase()}`, margin + 4, y + 6.5);
    doc.text(`BENCHMARK PEER: ${report.benchmarkCountry}`, margin + 60, y + 6.5);
    doc.text(`EVALUATION YEAR: ${report.year}`, margin + 125, y + 6.5);
    y += 16;

    // 1. Executive Summary
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    doc.setTextColor(15, 23, 42);
    doc.text("1. Executive Summary", margin, y);
    y += 5;

    doc.setFillColor(240, 249, 255);
    doc.setDrawColor(186, 230, 253);
    const summaryLines = doc.splitTextToSize(report.executiveSummary, pageWidth - margin * 2 - 8);
    const summaryBoxHeight = Math.max(14, summaryLines.length * 4 + 6);

    doc.rect(margin, y, pageWidth - margin * 2, summaryBoxHeight, "FD");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(3, 105, 161);
    doc.text(summaryLines, margin + 4, y + 5);
    y += summaryBoxHeight + 8;

    const checkOverflow = (neededHeight: number) => {
      if (y + neededHeight > pageHeight - 15) {
        doc.addPage();
        y = 20;
      }
    };

    // 2. Key Strategic Indicators Table
    checkOverflow(35);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    doc.setTextColor(15, 23, 42);
    doc.text("2. Key Strategic Indicators", margin, y);
    y += 5;

    doc.setFillColor(241, 245, 249);
    doc.rect(margin, y, pageWidth - margin * 2, 6, "F");
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(51, 65, 85);
    doc.text("Indicator", margin + 3, y + 4.5);
    doc.text("Category", margin + 55, y + 4.5);
    doc.text("Global Rank", margin + 95, y + 4.5);
    doc.text("Score", margin + 130, y + 4.5);
    doc.text("Source", margin + 155, y + 4.5);
    y += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);

    report.keyIndicators.slice(0, 6).forEach((ind) => {
      checkOverflow(6);
      doc.text(ind.name.slice(0, 28), margin + 3, y + 4);
      doc.text(ind.category.slice(0, 20), margin + 55, y + 4);
      doc.setFont("helvetica", "bold");
      doc.text(ind.globalRank, margin + 95, y + 4);
      doc.setFont("helvetica", "normal");
      doc.text(String(ind.score), margin + 130, y + 4);
      doc.text(ind.source.slice(0, 18), margin + 155, y + 4);
      doc.setDrawColor(241, 245, 249);
      doc.line(margin, y + 5.5, pageWidth - margin, y + 5.5);
      y += 6;
    });

    y += 5;

    // 3. Category Performance Scores Table
    checkOverflow(35);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    doc.setTextColor(15, 23, 42);
    doc.text("3. Category Performance Scores", margin, y);
    y += 5;

    doc.setFillColor(241, 245, 249);
    doc.rect(margin, y, pageWidth - margin * 2, 6, "F");
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(51, 65, 85);
    doc.text("Category", margin + 3, y + 4.5);
    doc.text("Overall Score", margin + 65, y + 4.5);
    doc.text("Global Rank", margin + 110, y + 4.5);
    doc.text("Top Peer", margin + 150, y + 4.5);
    y += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);

    report.categoryPerformance.forEach((cat) => {
      checkOverflow(6);
      doc.text(cat.name, margin + 3, y + 4);
      doc.text(`${cat.score} / 100`, margin + 65, y + 4);
      doc.setFont("helvetica", "bold");
      doc.text(cat.globalRank, margin + 110, y + 4);
      doc.setFont("helvetica", "normal");
      doc.text(cat.topPeer, margin + 150, y + 4);
      doc.setDrawColor(241, 245, 249);
      doc.line(margin, y + 5.5, pageWidth - margin, y + 5.5);
      y += 6;
    });

    y += 5;

    // 4. Strategic Strengths & Improvement Areas
    checkOverflow(30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    doc.setTextColor(15, 23, 42);
    doc.text("4. Key Strategic Insights", margin, y);
    y += 5;

    doc.setFontSize(8.5);
    doc.setTextColor(22, 101, 52);
    doc.text("Top Strengths:", margin, y);
    y += 4.5;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);
    report.strengths.forEach((str) => {
      checkOverflow(5);
      const lines = doc.splitTextToSize(`• ${str}`, pageWidth - margin * 2);
      doc.text(lines, margin + 3, y);
      y += lines.length * 3.8;
    });

    y += 3;
    checkOverflow(20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(153, 27, 27);
    doc.text("Priority Improvement Areas:", margin, y);
    y += 4.5;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);
    report.areasForImprovement.forEach((area) => {
      checkOverflow(5);
      const lines = doc.splitTextToSize(`• ${area}`, pageWidth - margin * 2);
      doc.text(lines, margin + 3, y);
      y += lines.length * 3.8;
    });

    y += 5;

    // 5. AI Recommendations
    checkOverflow(25);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    doc.setTextColor(15, 23, 42);
    doc.text("5. Gemini AI Executive Recommendations", margin, y);
    y += 5;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(126, 34, 206);
    report.aiRecommendations.forEach((rec, idx) => {
      checkOverflow(5);
      const lines = doc.splitTextToSize(`${idx + 1}. ${rec}`, pageWidth - margin * 2);
      doc.text(lines, margin + 3, y);
      y += lines.length * 3.8 + 1.5;
    });

    // Document Footer
    const pageCount = (doc.internal as any).getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(148, 163, 184);
      doc.line(margin, pageHeight - 10, pageWidth - margin, pageHeight - 10);
      doc.text(
        `IndiaLens AI Platform • Confidential Official Benchmark Data • Generated ${report.generatedAt}`,
        margin,
        pageHeight - 6
      );
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 15, pageHeight - 6);
    }

    doc.save(`IndiaLensAI_Report_${report.year}.pdf`);
  } catch (e) {
    console.error("jsPDF generation error:", e);
  }
}

