import { GeneratedReport } from "./report-data";

/**
 * Utility function to trigger a CSV download for any GeneratedReport
 */
export function exportReportCSV(report: GeneratedReport) {
  const lines: string[] = [];

  // Metadata
  lines.push(`"INDIALENS AI INTELLIGENCE REPORT"`);
  lines.push(`"Title","${report.title.replace(/"/g, '""')}"`);
  lines.push(`"Report Type","${report.type.toUpperCase()}"`);
  lines.push(`"Evaluation Year","${report.year}"`);
  lines.push(`"Benchmark Target","${report.benchmarkCountry}"`);
  lines.push(`"Generated Date","${report.generatedAt}"`);
  lines.push("");

  // Executive Summary
  lines.push(`"EXECUTIVE SUMMARY"`);
  lines.push(`"${report.executiveSummary.replace(/"/g, '""')}"`);
  lines.push("");

  // Key Strategic Indicators Table
  lines.push(`"KEY STRATEGIC INDICATORS"`);
  lines.push(`"Indicator","Category","Global Rank","Metric Score","Change","Status","Data Source"`);
  report.keyIndicators.forEach((ind) => {
    lines.push(
      `"${ind.name}","${ind.category}","${ind.globalRank}","${ind.score}","${ind.change}","${ind.status}","${ind.source}"`
    );
  });
  lines.push("");

  // Category Performance Table
  lines.push(`"CATEGORY PERFORMANCE BENCHMARKS"`);
  lines.push(`"Category","Overall Score (0-100)","Global Rank","Top Global Peer","Performance Gap","Status"`);
  report.categoryPerformance.forEach((cat) => {
    lines.push(
      `"${cat.name}","${cat.score}","${cat.globalRank}","${cat.topPeer}","${cat.gap}","${cat.status}"`
    );
  });
  lines.push("");

  // Historical Trends
  lines.push(`"HISTORICAL MULTI-YEAR TRAJECTORY"`);
  lines.push(`"Year","Rank / Index Score","Key Milestone"`);
  report.historicalTrends.forEach((t) => {
    lines.push(`"${t.year}","${t.score} (${t.rank})","${t.event.replace(/"/g, '""')}"`);
  });
  lines.push("");

  // Bilateral Comparison if applicable
  if (report.comparisonData) {
    lines.push(`"BILATERAL COMPARISON WITH ${report.benchmarkCountry.toUpperCase()}"`);
    lines.push(`"Indicator","Category","India Value","India Rank","${report.benchmarkCountry} Value","${report.benchmarkCountry} Rank","Leader"`);
    report.comparisonData.rows.forEach((row) => {
      lines.push(
        `"${row.indicator}","${row.category}","${row.indiaVal}","${row.indiaRank}","${row.peerVal}","${row.peerRank}","${row.leader}"`
      );
    });
    lines.push("");
  }

  // Strengths
  lines.push(`"KEY STRATEGIC STRENGTHS"`);
  report.strengths.forEach((str, i) => {
    lines.push(`"${i + 1}","${str.replace(/"/g, '""')}"`);
  });
  lines.push("");

  // Areas for Improvement
  lines.push(`"AREAS FOR POLICY IMPROVEMENT"`);
  report.areasForImprovement.forEach((area, i) => {
    lines.push(`"${i + 1}","${area.replace(/"/g, '""')}"`);
  });
  lines.push("");

  // AI Recommendations
  lines.push(`"AI EXECUTIVE RECOMMENDATIONS"`);
  report.aiRecommendations.forEach((rec, i) => {
    lines.push(`"${i + 1}","${rec.replace(/"/g, '""')}"`);
  });
  lines.push("");

  // Data Sources
  lines.push(`"DATA SOURCES & CITATIONS"`);
  report.dataSources.forEach((src) => {
    lines.push(`"${src.replace(/"/g, '""')}"`);
  });
  lines.push("");
  lines.push(`"Report generated by IndiaLens AI Platform - Confidential & Official Benchmark Data"`);

  const csvContent = lines.join("\n");
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute(
    "download",
    `IndiaLens_${report.type.toUpperCase()}_Report_${report.year}.csv`
  );
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Utility function to generate a printable PDF view for any GeneratedReport
 */
export function exportReportPDF(report: GeneratedReport) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to export the PDF report.");
    return;
  }

  const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>${report.title} - IndiaLens AI Report</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
          font-family: 'Inter', system-ui, -apple-system, sans-serif;
          color: #0f172a;
          background: #ffffff;
          padding: 40px;
          line-height: 1.5;
          font-size: 13px;
        }
        .header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          border-b: 3px solid #3b82f6;
          padding-bottom: 20px;
          margin-bottom: 25px;
        }
        .logo {
          font-size: 22px;
          font-weight: 800;
          color: #1e3a8a;
          letter-spacing: -0.5px;
        }
        .badge {
          background: #eff6ff;
          color: #2563eb;
          border: 1px solid #bfdbfe;
          padding: 4px 12px;
          border-radius: 20px;
          font-weight: 700;
          font-size: 11px;
          text-transform: uppercase;
        }
        .meta-bar {
          display: flex;
          gap: 20px;
          background: #f8fafc;
          border: 1px solid #e2e8f0;
          padding: 12px 18px;
          border-radius: 10px;
          margin-bottom: 25px;
          font-size: 12px;
        }
        .meta-item { display: flex; flex-direction: column; }
        .meta-label { font-size: 10px; color: #64748b; font-weight: 700; text-transform: uppercase; }
        .meta-val { font-weight: 700; color: #0f172a; }
        .section-title {
          font-size: 16px;
          font-weight: 800;
          color: #1e293b;
          border-left: 4px solid #3b82f6;
          padding-left: 10px;
          margin-top: 25px;
          margin-bottom: 12px;
        }
        .summary-box {
          background: #f0f9ff;
          border: 1px solid #bae6fd;
          padding: 16px;
          border-radius: 10px;
          font-size: 13px;
          color: #0369a1;
          margin-bottom: 20px;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 20px;
          font-size: 12px;
        }
        th, td {
          padding: 10px 12px;
          text-align: left;
          border-bottom: 1px solid #e2e8f0;
        }
        th {
          background: #f1f5f9;
          font-weight: 700;
          color: #334155;
          text-transform: uppercase;
          font-size: 10px;
        }
        tr:nth-child(even) { background: #fafafa; }
        .list-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 15px;
          margin-bottom: 20px;
        }
        .card-box {
          border: 1px solid #e2e8f0;
          border-radius: 10px;
          padding: 15px;
          background: #ffffff;
        }
        .card-box-title {
          font-weight: 700;
          font-size: 13px;
          margin-bottom: 8px;
        }
        .card-box-title.green { color: #166534; }
        .card-box-title.red { color: #991b1b; }
        ul { padding-left: 18px; font-size: 12px; }
        li { margin-bottom: 6px; }
        .ai-box {
          background: #faf5ff;
          border: 1px solid #e9d5ff;
          padding: 16px;
          border-radius: 10px;
          margin-bottom: 20px;
        }
        .ai-title {
          color: #7e22ce;
          font-weight: 800;
          font-size: 13px;
          margin-bottom: 8px;
        }
        .footer {
          margin-top: 40px;
          border-t: 2px solid #e2e8f0;
          padding-top: 15px;
          display: flex;
          justify-content: space-between;
          font-size: 11px;
          color: #64748b;
        }
        @media print {
          body { padding: 20px; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div className="header">
        <div>
          <div className="logo">IndiaLens AI</div>
          <div style="font-size: 11px; color: #64748b; font-weight: 600;">Global Intelligence & Benchmark Platform</div>
        </div>
        <span className="badge">${report.type.toUpperCase()} REPORT</span>
      </div>

      <h1 style="font-size: 20px; font-weight: 800; margin-bottom: 5px; color: #0f172a;">${report.title}</h1>
      <p style="font-size: 13px; color: #475569; margin-bottom: 20px;">${report.subtitle}</p>

      <div className="meta-bar">
        <div className="meta-item">
          <span className="meta-label">Evaluation Year</span>
          <span className="meta-val">${report.year}</span>
        </div>
        <div className="meta-item">
          <span className="meta-label">Report Type</span>
          <span className="meta-val">${report.type.toUpperCase()}</span>
        </div>
        <div className="meta-item">
          <span className="meta-label">Benchmark Peer</span>
          <span className="meta-val">${report.benchmarkCountry}</span>
        </div>
        <div className="meta-item">
          <span className="meta-label">Generated Date</span>
          <span className="meta-val">${report.generatedAt}</span>
        </div>
      </div>

      <div className="section-title">Executive Summary</div>
      <div className="summary-box">
        ${report.executiveSummary}
      </div>

      <div className="section-title">Key Strategic Indicators</div>
      <table>
        <thead>
          <tr>
            <th>Indicator</th>
            <th>Category</th>
            <th>Global Rank</th>
            <th>Score</th>
            <th>Change</th>
            <th>Source</th>
          </tr>
        </thead>
        <tbody>
          ${report.keyIndicators
            .map(
              (ind) => `
            <tr>
              <td><strong>${ind.name}</strong></td>
              <td>${ind.category}</td>
              <td><strong>${ind.globalRank}</strong></td>
              <td>${ind.score}</td>
              <td style="color: ${ind.status === "improved" ? "#16a34a" : "#dc2626"}; font-weight: bold;">${ind.change}</td>
              <td>${ind.source}</td>
            </tr>
          `
            )
            .join("")}
        </tbody>
      </table>

      <div className="section-title">Category Performance</div>
      <table>
        <thead>
          <tr>
            <th>Category</th>
            <th>Overall Score</th>
            <th>Global Rank</th>
            <th>Top Global Peer</th>
            <th>Performance Gap</th>
          </tr>
        </thead>
        <tbody>
          ${report.categoryPerformance
            .map(
              (cat) => `
            <tr>
              <td><strong>${cat.name}</strong></td>
              <td>${cat.score} / 100</td>
              <td><strong>${cat.globalRank}</strong></td>
              <td>${cat.topPeer}</td>
              <td>${cat.gap}</td>
            </tr>
          `
            )
            .join("")}
        </tbody>
      </table>

      <div className="list-grid">
        <div className="card-box">
          <div className="card-box-title green">Key Strategic Strengths</div>
          <ul>
            ${report.strengths.map((s) => `<li>${s}</li>`).join("")}
          </ul>
        </div>

        <div className="card-box">
          <div className="card-box-title red">Areas for Improvement</div>
          <ul>
            ${report.areasForImprovement.map((a) => `<li>${a}</li>`).join("")}
          </ul>
        </div>
      </div>

      <div className="section-title">AI Strategic Recommendations</div>
      <div className="ai-box">
        <div className="ai-title">Gemini 2.5 Flash Actionable Priorities</div>
        <ul>
          ${report.aiRecommendations.map((r) => `<li>${r}</li>`).join("")}
        </ul>
      </div>

      <div className="section-title">Data Sources & Citations</div>
      <ul>
        ${report.dataSources.map((src) => `<li>${src}</li>`).join("")}
      </ul>

      <div className="footer">
        <div>Official Intelligence Document • Generated by <strong>IndiaLens AI</strong></div>
        <div>Confidential Benchmark Data</div>
      </div>

      <script>
        window.onload = function() {
          window.print();
        };
      </script>
    </body>
    </html>
  `;

  printWindow.document.open();
  printWindow.document.write(htmlContent);
  printWindow.document.close();
}
