export type CommandCategory = "pages" | "countries" | "indicators" | "categories" | "ai-prompts" | "actions";

export interface CommandItem {
  id: string;
  title: string;
  description: string;
  category: CommandCategory;
  badge?: string;
  iconName: string; // Lucide icon identifier
  keywords: string[];
  action: {
    type: "navigate" | "ai-prompt" | "custom-action";
    target: string;
    extraParams?: Record<string, string>;
  };
}

export const commandItems: CommandItem[] = [
  // 1. Pages Navigation
  {
    id: "page-dashboard",
    title: "Dashboard",
    description: "Global Intelligence Dashboard & key performance indicators",
    category: "pages",
    badge: "Page",
    iconName: "LayoutDashboard",
    keywords: ["dashboard", "home", "overview", "kpis", "indicators", "main"],
    action: { type: "navigate", target: "/dashboard" },
  },
  {
    id: "page-compare",
    title: "Country Comparison",
    description: "Cross-country side-by-side indicator benchmarks",
    category: "pages",
    badge: "Page",
    iconName: "ArrowLeftRight",
    keywords: ["compare", "comparison", "benchmark", "vs", "versus", "country"],
    action: { type: "navigate", target: "/compare" },
  },
  {
    id: "page-world-map",
    title: "Interactive World Map",
    description: "Geographic evaluation map across 15+ world economies",
    category: "pages",
    badge: "Page",
    iconName: "Globe",
    keywords: ["world map", "map", "globe", "geographic", "countries", "spatial"],
    action: { type: "navigate", target: "/world-map" },
  },
  {
    id: "page-ai-insights",
    title: "AI Insights & Assistant",
    description: "AI-synthesized reports and interactive intelligence chatbot",
    category: "pages",
    badge: "Page",
    iconName: "Brain",
    keywords: ["ai insights", "ai", "chat", "assistant", "bot", "report", "intelligence"],
    action: { type: "navigate", target: "/ai-insights" },
  },

  // 2. Direct Actions / AI Commands
  {
    id: "action-compare-ind-chn",
    title: "Compare India and China",
    description: "Direct side-by-side benchmark of India (IND) vs China (CHN)",
    category: "actions",
    badge: "Command",
    iconName: "ArrowLeftRight",
    keywords: ["compare india and china", "india vs china", "ind vs chn", "china"],
    action: { type: "navigate", target: "/compare?c1=IND&c2=CHN" },
  },
  {
    id: "action-compare-ind-usa",
    title: "Compare India and USA",
    description: "Direct side-by-side benchmark of India (IND) vs United States (USA)",
    category: "actions",
    badge: "Command",
    iconName: "ArrowLeftRight",
    keywords: ["compare india and usa", "india vs usa", "ind vs usa", "america"],
    action: { type: "navigate", target: "/compare?c1=IND&c2=USA" },
  },
  {
    id: "action-explain-hdi",
    title: "Explain HDI",
    description: "Ask IndiaLens AI to analyze India's Human Development Index ranking",
    category: "ai-prompts",
    badge: "AI Command",
    iconName: "Sparkles",
    keywords: ["explain hdi", "hdi", "human development index", "health spending"],
    action: { type: "ai-prompt", target: "Explain India's Human Development Index ranking in detail." },
  },
  {
    id: "action-generate-report",
    title: "Generate Report",
    description: "Export full multi-year intelligence report for India",
    category: "actions",
    badge: "Action",
    iconName: "Download",
    keywords: ["generate report", "export report", "download report", "print", "pdf"],
    action: { type: "custom-action", target: "export-report" },
  },

  // 3. Strategic Categories
  {
    id: "cat-technology",
    title: "Technology",
    description: "Digital infrastructure, patent filings, AI readiness & IT exports (#12 Global)",
    category: "categories",
    badge: "Domain",
    iconName: "Cpu",
    keywords: ["technology", "tech", "digital", "patents", "software", "it"],
    action: { type: "navigate", target: "/dashboard#technology" },
  },
  {
    id: "cat-digital-gov",
    title: "Digital Government",
    description: "UPI transactions, e-governance services & Digital Public Goods (#9 Global)",
    category: "categories",
    badge: "Domain",
    iconName: "Landmark",
    keywords: ["digital government", "upi", "aadhaar", "digilocker", "fintech", "dpi"],
    action: { type: "navigate", target: "/dashboard#digital-government" },
  },
  {
    id: "cat-economy",
    title: "Economy",
    description: "GDP growth, FDI inflows, fiscal deficit & exports (#5 Global)",
    category: "categories",
    badge: "Domain",
    iconName: "TrendingUp",
    keywords: ["economy", "gdp", "fdi", "exports", "financial", "growth"],
    action: { type: "navigate", target: "/dashboard#economy" },
  },
  {
    id: "cat-healthcare",
    title: "Healthcare",
    description: "Universal health coverage, life expectancy & hospital capacity (#92 Global)",
    category: "categories",
    badge: "Domain",
    iconName: "HeartPulse",
    keywords: ["healthcare", "health", "ayushman bharat", "hospitals", "medical"],
    action: { type: "navigate", target: "/dashboard#healthcare" },
  },
  {
    id: "cat-education",
    title: "Education",
    description: "STEM graduates, higher education enrollment & literacy rates (#72 Global)",
    category: "categories",
    badge: "Domain",
    iconName: "GraduationCap",
    keywords: ["education", "stem", "universities", "literacy", "students"],
    action: { type: "navigate", target: "/dashboard#education" },
  },
  {
    id: "cat-governance",
    title: "Governance",
    description: "Government effectiveness, rule of law & regulatory quality (#68 Global)",
    category: "categories",
    badge: "Domain",
    iconName: "Building2",
    keywords: ["governance", "rule of law", "regulations", "policy", "government"],
    action: { type: "navigate", target: "/dashboard#governance" },
  },
  {
    id: "cat-environment",
    title: "Environment",
    description: "Renewable energy adoption, air quality & carbon intensity (#110 Global)",
    category: "categories",
    badge: "Domain",
    iconName: "Leaf",
    keywords: ["environment", "green", "solar", "emissions", "climate", "air quality"],
    action: { type: "navigate", target: "/dashboard#environment" },
  },
  {
    id: "cat-safety",
    title: "Safety",
    description: "Cybersecurity preparedness, internal security & peace index (#88 Global)",
    category: "categories",
    badge: "Domain",
    iconName: "ShieldCheck",
    keywords: ["safety", "cybersecurity", "peace", "security", "defense"],
    action: { type: "navigate", target: "/dashboard#safety" },
  },
  {
    id: "cat-equality",
    title: "Equality",
    description: "Gender parity, income distribution & economic opportunity (#105 Global)",
    category: "categories",
    badge: "Domain",
    iconName: "Scale",
    keywords: ["equality", "gender gap", "parity", "income", "inclusion"],
    action: { type: "navigate", target: "/dashboard#equality" },
  },
  {
    id: "cat-society",
    title: "Society",
    description: "Human development, demographic dividend & social mobility (#84 Global)",
    category: "categories",
    badge: "Domain",
    iconName: "Users",
    keywords: ["society", "demographics", "welfare", "human development"],
    action: { type: "navigate", target: "/dashboard#society" },
  },

  // 4. Countries Benchmarked
  {
    id: "country-ind",
    title: "India (IND)",
    description: "Ranked #5 Global Economy ($3.75T GDP), #9 Digital Gov, #39 GII",
    category: "countries",
    badge: "🇮🇳 Country",
    iconName: "MapPin",
    keywords: ["india", "ind", "bharat", "delhi", "bengaluru"],
    action: { type: "navigate", target: "/world-map?country=IND" },
  },
  {
    id: "country-chn",
    title: "China (CHN)",
    description: "Ranked #2 Global Economy ($17.7T GDP), #7 Digital Gov, #11 GII",
    category: "countries",
    badge: "🇨🇳 Country",
    iconName: "MapPin",
    keywords: ["china", "chn", "beijing", "shanghai"],
    action: { type: "navigate", target: "/compare?c1=IND&c2=CHN" },
  },
  {
    id: "country-usa",
    title: "United States (USA)",
    description: "Ranked #1 Global Economy ($26.9T GDP), #3 Digital Gov, #3 GII",
    category: "countries",
    badge: "🇺🇸 Country",
    iconName: "MapPin",
    keywords: ["united states", "usa", "america", "us", "washington"],
    action: { type: "navigate", target: "/compare?c1=IND&c2=USA" },
  },
  {
    id: "country-gbr",
    title: "United Kingdom (GBR)",
    description: "Ranked #6 Global Economy ($3.1T GDP), #4 GII, #18 HDI",
    category: "countries",
    badge: "🇬🇧 Country",
    iconName: "MapPin",
    keywords: ["united kingdom", "uk", "gbr", "britain", "london"],
    action: { type: "navigate", target: "/compare?c1=IND&c2=GBR" },
  },
  {
    id: "country-jpn",
    title: "Japan (JPN)",
    description: "Ranked #4 Global Economy ($4.2T GDP), #13 GII, #22 HDI",
    category: "countries",
    badge: "🇯🇵 Country",
    iconName: "MapPin",
    keywords: ["japan", "jpn", "tokyo"],
    action: { type: "navigate", target: "/compare?c1=IND&c2=JPN" },
  },
  {
    id: "country-deu",
    title: "Germany (DEU)",
    description: "Ranked #3 Global Economy ($4.4T GDP), #8 GII, #7 HDI",
    category: "countries",
    badge: "🇩🇪 Country",
    iconName: "MapPin",
    keywords: ["germany", "deu", "berlin"],
    action: { type: "navigate", target: "/compare?c1=IND&c2=DEU" },
  },
  {
    id: "country-sgp",
    title: "Singapore (SGP)",
    description: "Ranked #1 Logistics Performance Index, #5 GII, #9 HDI",
    category: "countries",
    badge: "🇸🇬 Country",
    iconName: "MapPin",
    keywords: ["singapore", "sgp"],
    action: { type: "navigate", target: "/compare?c1=IND&c2=SGP" },
  },

  // 5. Key Indicators
  {
    id: "ind-gdp",
    title: "GDP Rank & Economic Scale",
    description: "India ranked #5 Nominal GDP ($3.75T) with ~7.2% real growth",
    category: "indicators",
    badge: "Indicator",
    iconName: "BarChart3",
    keywords: ["gdp", "gdp rank", "economic scale", "trillion", "economy"],
    action: { type: "navigate", target: "/dashboard" },
  },
  {
    id: "ind-gii",
    title: "Global Innovation Index (WIPO)",
    description: "India ranked #39 globally (up from #46 in 2022)",
    category: "indicators",
    badge: "Indicator",
    iconName: "Sparkles",
    keywords: ["innovation", "gii", "wipo", "patents", "r&d"],
    action: { type: "ai-prompt", target: "Why is India's Global Innovation Index rank improving?" },
  },
  {
    id: "ind-ai",
    title: "Government AI Readiness Index",
    description: "India ranked #32 globally (Oxford Insights), up 4 positions",
    category: "indicators",
    badge: "Indicator",
    iconName: "Brain",
    keywords: ["ai readiness", "ai", "compute", "gpu", "indiaai"],
    action: { type: "ai-prompt", target: "Summarize India's AI Readiness index and computing outlay." },
  },
  {
    id: "ind-hdi",
    title: "Human Development Index (UNDP)",
    description: "India ranked #134 globally with 0.644 Medium score",
    category: "indicators",
    badge: "Indicator",
    iconName: "Users",
    keywords: ["hdi", "human development", "undp", "life expectancy", "education"],
    action: { type: "ai-prompt", target: "Explain India's Human Development Index ranking and bottlenecks." },
  },
  {
    id: "ind-press",
    title: "World Press Freedom Index (RSF)",
    description: "India ranked #159 globally (Reporters Without Borders)",
    category: "indicators",
    badge: "Indicator",
    iconName: "FileText",
    keywords: ["press freedom", "rsf", "media", "journalism"],
    action: { type: "ai-prompt", target: "Explain India's Press Freedom index ranking." },
  },
];
