export type CommandCategory =
  | "pages"
  | "countries"
  | "indicators"
  | "categories"
  | "ai-prompts"
  | "actions";

export interface CommandItem {
  id: string;
  title: string;
  description: string;
  category: CommandCategory;
  badge?: string;
  iconName: string; // Lucide icon identifier
  keywords: string[];
  action: {
    type: "navigate" | "ai-prompt" | "custom-action";
    target: string;
    extraParams?: Record<string, string>;
  };
}

export const commandItems: CommandItem[] = [
  // ----------------------------------------------------------------------
  // 1. NAVIGATION PAGES (All 8 pages)
  // ----------------------------------------------------------------------
  {
    id: "page-dashboard",
    title: "Dashboard",
    description: "Global Intelligence Dashboard & key performance metrics",
    category: "pages",
    badge: "Page",
    iconName: "LayoutDashboard",
    keywords: ["dashboard", "home", "overview", "kpis", "indicators", "main"],
    action: { type: "navigate", target: "/dashboard" },
  },
  {
    id: "page-categories",
    title: "Categories",
    description: "Explore India's performance across 10 strategic development pillars",
    category: "pages",
    badge: "Page",
    iconName: "Layers",
    keywords: ["categories", "category", "pillars", "domains", "economy", "tech", "health", "edu", "gov"],
    action: { type: "navigate", target: "/categories" },
  },
  {
    id: "page-compare",
    title: "Compare",
    description: "Cross-country side-by-side indicator benchmarks",
    category: "pages",
    badge: "Page",
    iconName: "ArrowLeftRight",
    keywords: ["compare", "comparison", "benchmark", "vs", "versus", "country"],
    action: { type: "navigate", target: "/compare" },
  },
  {
    id: "page-world-map",
    title: "World Map",
    description: "Geographic evaluation map across 15+ world economies",
    category: "pages",
    badge: "Page",
    iconName: "Globe",
    keywords: ["world map", "map", "globe", "geographic", "countries", "spatial"],
    action: { type: "navigate", target: "/world-map" },
  },
  {
    id: "page-trends",
    title: "Trends",
    description: "Multi-year historical trajectory & longitudinal trend charts (2020-2025)",
    category: "pages",
    badge: "Page",
    iconName: "TrendingUp",
    keywords: ["trends", "historical", "trajectory", "timeline", "longitudinal", "multi-year"],
    action: { type: "navigate", target: "/trends" },
  },
  {
    id: "page-ai-insights",
    title: "AI Insights",
    description: "AI-synthesized reports and interactive intelligence chatbot",
    category: "pages",
    badge: "Page",
    iconName: "Brain",
    keywords: ["ai insights", "ai", "chat", "assistant", "bot", "intelligence", "gemini"],
    action: { type: "navigate", target: "/ai-insights" },
  },
  {
    id: "page-reports",
    title: "Reports",
    description: "Generate, preview & export professional executive intelligence reports",
    category: "pages",
    badge: "Page",
    iconName: "FileText",
    keywords: ["reports", "report", "pdf", "export", "executive summary", "briefing"],
    action: { type: "navigate", target: "/reports" },
  },
  {
    id: "page-sources",
    title: "Sources",
    description: "Trusted international data sources, datasets catalog, normalization methodology governance",
    category: "pages",
    badge: "Page",
    iconName: "Database",
    keywords: ["sources", "data sources", "world bank", "imf", "un", "provenance", "methodology"],
    action: { type: "navigate", target: "/sources" },
  },
  {
    id: "page-methodology",
    title: "Methodology",
    description: "Data collection, normalization formula, percentile calculation & pipeline governance",
    category: "pages",
    badge: "Page",
    iconName: "Sliders",
    keywords: ["methodology", "pipeline", "normalization", "percentile", "formula", "trusted orgs", "ranking"],
    action: { type: "navigate", target: "/methodology" },
  },
  {
    id: "page-about",
    title: "About",
    description: "What is IndiaLens AI, mission, technology stack, Gemini AI capabilities & future roadmap",
    category: "pages",
    badge: "Page",
    iconName: "Info",
    keywords: ["about", "mission", "indialens", "tech stack", "features", "roadmap", "gemini"],
    action: { type: "navigate", target: "/about" },
  },
  {
    id: "page-contact",
    title: "Contact & Support",
    description: "Get in touch, send feedback, report data anomalies, connect on LinkedIn with Meghana Merla",
    category: "pages",
    badge: "Page",
    iconName: "Mail",
    keywords: ["contact", "support", "feedback", "bug report", "anomaly", "meghana merla", "linkedin", "email"],
    action: { type: "navigate", target: "/contact" },
  },

  // ----------------------------------------------------------------------
  // 2. CATEGORIES (All 10 development pillars with /categories?category=<slug>)
  // ----------------------------------------------------------------------
  {
    id: "cat-economy",
    title: "Economy",
    description: "GDP growth, FDI inflows, fiscal deficit & exports (#5 Global Rank)",
    category: "categories",
    badge: "Category",
    iconName: "TrendingUp",
    keywords: ["economy", "eco", "economic", "gdp", "fdi", "exports", "financial", "growth", "finance", "market"],
    action: { type: "navigate", target: "/categories?category=economy" },
  },
  {
    id: "cat-society",
    title: "Society",
    description: "Human development, demographic dividend & social wellbeing (#64 Global Rank)",
    category: "categories",
    badge: "Category",
    iconName: "Users",
    keywords: ["society", "soc", "demographics", "welfare", "human development", "hdi", "happiness", "wellbeing"],
    action: { type: "navigate", target: "/categories?category=society" },
  },
  {
    id: "cat-governance",
    title: "Governance",
    description: "Government effectiveness, rule of law & regulatory quality (#78 Global Rank)",
    category: "categories",
    badge: "Category",
    iconName: "Building2",
    keywords: ["governance", "government", "gov", "policy", "rule of law", "regulations", "rules", "regulation", "cpi"],
    action: { type: "navigate", target: "/categories?category=governance" },
  },
  {
    id: "cat-technology",
    title: "Technology & Innovation",
    description: "Digital infrastructure, patent filings, AI readiness & IT exports (#39 Global Rank)",
    category: "categories",
    badge: "Category",
    iconName: "Cpu",
    keywords: ["technology", "tech", "ai", "innovation", "innov", "digital", "software", "r&d", "patents", "gii"],
    action: { type: "navigate", target: "/categories?category=technology" },
  },
  {
    id: "cat-education",
    title: "Education",
    description: "STEM graduates, higher education enrollment & literacy rates (#52 Global Rank)",
    category: "categories",
    badge: "Category",
    iconName: "GraduationCap",
    keywords: ["education", "edu", "school", "university", "stem", "literacy", "students", "schools"],
    action: { type: "navigate", target: "/categories?category=education" },
  },
  {
    id: "cat-healthcare",
    title: "Healthcare",
    description: "Universal health coverage, life expectancy & pharma scale (#71 Global Rank)",
    category: "categories",
    badge: "Category",
    iconName: "HeartPulse",
    keywords: ["healthcare", "health", "heal", "medical", "hospital", "ayushman", "doctor", "uhc", "pharma"],
    action: { type: "navigate", target: "/categories?category=healthcare" },
  },
  {
    id: "cat-environment",
    title: "Environment",
    description: "Renewable energy adoption, CCPI climate action & forest cover (#44 Global Rank)",
    category: "categories",
    badge: "Category",
    iconName: "Leaf",
    keywords: ["environment", "env", "green", "solar", "emissions", "climate", "air quality", "ccpi"],
    action: { type: "navigate", target: "/categories?category=environment" },
  },
  {
    id: "cat-safety",
    title: "Safety",
    description: "Cybersecurity preparedness, disaster response & peace index (#42 Global Rank)",
    category: "categories",
    badge: "Category",
    iconName: "ShieldCheck",
    keywords: ["safety", "safe", "cybersecurity", "cyber", "peace", "security", "defense", "gci"],
    action: { type: "navigate", target: "/categories?category=safety" },
  },
  {
    id: "cat-equality",
    title: "Equality",
    description: "Gender parity, income distribution & account ownership parity (#88 Global Rank)",
    category: "categories",
    badge: "Category",
    iconName: "Scale",
    keywords: ["equality", "eq", "gender gap", "gender", "parity", "income", "inclusion", "social mobility"],
    action: { type: "navigate", target: "/categories?category=equality" },
  },
  {
    id: "cat-digital-gov",
    title: "Digital Government",
    description: "UPI transactions, Aadhaar identity, DigiLocker & E-Participation (#18 Global Rank)",
    category: "categories",
    badge: "Category",
    iconName: "Landmark",
    keywords: ["digital government", "digital gov", "digit", "gov", "upi", "aadhaar", "digilocker", "dpi", "egdi"],
    action: { type: "navigate", target: "/categories?category=digital-government" },
  },

  // ----------------------------------------------------------------------
  // 3. MAJOR INDICATORS (All required indicators with /categories?indicator=<slug>)
  // ----------------------------------------------------------------------
  {
    id: "ind-gdp",
    title: "GDP",
    description: "India ranked #5 Globally ($3.75 Trillion) in Nominal GDP output",
    category: "indicators",
    badge: "Indicator",
    iconName: "BarChart3",
    keywords: ["gdp", "gross domestic product", "gdp rank", "economic scale", "trillion", "economy", "eco", "economic"],
    action: { type: "navigate", target: "/categories?indicator=gdp" },
  },
  {
    id: "ind-gdp-growth",
    title: "GDP Growth",
    description: "Real GDP Annual Growth Rate (~7.2% fastest growing major economy)",
    category: "indicators",
    badge: "Indicator",
    iconName: "TrendingUp",
    keywords: ["gdp growth", "real gdp growth", "growth rate", "economic growth", "gdp", "economy", "eco"],
    action: { type: "navigate", target: "/categories?indicator=gdp-growth" },
  },
  {
    id: "ind-gdp-per-capita",
    title: "GDP per Capita",
    description: "Per capita income distribution & purchasing power parity (PPP)",
    category: "indicators",
    badge: "Indicator",
    iconName: "BarChart3",
    keywords: ["gdp per capita", "per capita", "gdp", "income", "per capita gdp", "economy", "eco"],
    action: { type: "navigate", target: "/categories?indicator=gdp-per-capita" },
  },
  {
    id: "ind-inflation",
    title: "Inflation",
    description: "Consumer price index stability and RBI policy target management",
    category: "indicators",
    badge: "Indicator",
    iconName: "TrendingUp",
    keywords: ["inflation", "cpi inflation", "price stability", "rbi", "imf", "economy", "eco"],
    action: { type: "navigate", target: "/categories?indicator=inflation" },
  },
  {
    id: "ind-unemployment",
    title: "Unemployment",
    description: "Unemployment rate, labor force participation & employment momentum",
    category: "indicators",
    badge: "Indicator",
    iconName: "Users",
    keywords: ["unemployment", "unemployment rate", "jobs", "labor force", "employment", "workforce", "economy"],
    action: { type: "navigate", target: "/categories?indicator=unemployment" },
  },
  {
    id: "ind-hdi",
    title: "HDI",
    description: "Human Development Index (#134 Globally by UNDP with 0.644 score)",
    category: "indicators",
    badge: "Indicator",
    iconName: "Users",
    keywords: ["hdi", "human development index", "human development", "undp", "life expectancy", "society"],
    action: { type: "navigate", target: "/categories?indicator=hdi" },
  },
  {
    id: "ind-gii",
    title: "Global Innovation Index",
    description: "Global Innovation Index (GII) ranked #39 globally by WIPO",
    category: "indicators",
    badge: "Indicator",
    iconName: "Sparkles",
    keywords: ["global innovation index", "gii", "innovation", "innov", "wipo", "patents", "r&d", "tech", "technology"],
    action: { type: "navigate", target: "/categories?indicator=gii" },
  },
  {
    id: "ind-ai-readiness",
    title: "AI Readiness",
    description: "Government AI Readiness Index ranked #32 globally by Oxford Insights",
    category: "indicators",
    badge: "Indicator",
    iconName: "Brain",
    keywords: ["ai readiness", "ai", "government ai readiness", "oxford insights", "compute", "tech", "technology"],
    action: { type: "navigate", target: "/categories?indicator=ai-readiness" },
  },
  {
    id: "ind-healthcare-index",
    title: "Healthcare Index",
    description: "Universal Health Coverage (UHC) Index & health infrastructure scale by WHO",
    category: "indicators",
    badge: "Indicator",
    iconName: "HeartPulse",
    keywords: ["healthcare index", "healthcare", "health", "heal", "medical", "hospital", "uhc", "who"],
    action: { type: "navigate", target: "/categories?indicator=healthcare-index" },
  },
  {
    id: "ind-education-index",
    title: "Education Index",
    description: "STEM graduate volume & higher education ranking presence by UNESCO",
    category: "indicators",
    badge: "Indicator",
    iconName: "GraduationCap",
    keywords: ["education index", "education", "edu", "stem", "universities", "literacy", "school", "unesco"],
    action: { type: "navigate", target: "/categories?indicator=education-index" },
  },
  {
    id: "ind-cybersecurity",
    title: "Cybersecurity",
    description: "Global Cybersecurity Index (GCI) ranked Top 10 globally by ITU",
    category: "indicators",
    badge: "Indicator",
    iconName: "Lock",
    keywords: ["cybersecurity", "cyber", "gci", "global cybersecurity index", "itu", "security", "digital", "digit"],
    action: { type: "navigate", target: "/categories?indicator=cybersecurity" },
  },
  {
    id: "ind-peace",
    title: "Global Peace Index",
    description: "Societal safety, public order & conflict index by IEP",
    category: "indicators",
    badge: "Indicator",
    iconName: "ShieldCheck",
    keywords: ["global peace index", "global peace", "peace", "peace index", "safety", "security"],
    action: { type: "navigate", target: "/categories?indicator=global-peace" },
  },
  {
    id: "ind-press-freedom",
    title: "Press Freedom",
    description: "World Press Freedom Index media benchmarking by RSF",
    category: "indicators",
    badge: "Indicator",
    iconName: "FileText",
    keywords: ["press freedom", "press", "freedom of press", "rsf", "media", "journalism"],
    action: { type: "navigate", target: "/categories?indicator=press-freedom" },
  },
  {
    id: "ind-happiness",
    title: "Happiness",
    description: "World Happiness Index subjective wellbeing score by UN SDSN",
    category: "indicators",
    badge: "Indicator",
    iconName: "Smile",
    keywords: ["happiness", "world happiness index", "happiness index", "wellbeing", "society"],
    action: { type: "navigate", target: "/categories?indicator=happiness" },
  },
  {
    id: "ind-internet-penetration",
    title: "Internet Penetration",
    description: "Internet penetration, 5G adoption rate & rural digital connectivity",
    category: "indicators",
    badge: "Indicator",
    iconName: "Globe",
    keywords: ["internet penetration", "internet", "broadband", "web", "connectivity", "digital", "digit"],
    action: { type: "navigate", target: "/categories?indicator=internet-penetration" },
  },
  {
    id: "ind-gender-gap",
    title: "Gender Gap",
    description: "Global Gender Gap Index parity benchmarking by WEF",
    category: "indicators",
    badge: "Indicator",
    iconName: "Scale",
    keywords: ["gender gap", "gender", "parity", "equality", "wef", "women"],
    action: { type: "navigate", target: "/categories?indicator=gender-gap" },
  },
  {
    id: "ind-climate-change",
    title: "Climate Change",
    description: "Climate Change Performance Index (CCPI) ranked Top 10 globally by Germanwatch",
    category: "indicators",
    badge: "Indicator",
    iconName: "Leaf",
    keywords: ["climate change", "climate", "ccpi", "emissions", "environment", "renewable", "green"],
    action: { type: "navigate", target: "/categories?indicator=climate-change" },
  },
  {
    id: "ind-air-quality",
    title: "Air Quality",
    description: "Urban PM2.5 air quality index & environmental health exposure by IQAir",
    category: "indicators",
    badge: "Indicator",
    iconName: "Leaf",
    keywords: ["air quality", "pm2.5", "aqi", "iqair", "pollution", "environment", "climate"],
    action: { type: "navigate", target: "/categories?indicator=air-quality" },
  },

  // ----------------------------------------------------------------------
  // 4. COUNTRIES & ACTIONS
  // ----------------------------------------------------------------------
  {
    id: "country-ind",
    title: "India (IND)",
    description: "Ranked #5 Global Economy ($3.75T GDP), #18 Digital Gov, #39 GII",
    category: "countries",
    badge: "🇮🇳 Country",
    iconName: "MapPin",
    keywords: ["india", "ind", "bharat", "delhi", "bengaluru"],
    action: { type: "navigate", target: "/world-map?country=IND" },
  },
  {
    id: "country-usa",
    title: "United States (USA)",
    description: "Ranked #1 Global Economy ($26.9T GDP), #3 GII",
    category: "countries",
    badge: "🇺🇸 Country",
    iconName: "MapPin",
    keywords: ["united states", "usa", "america", "us", "washington"],
    action: { type: "navigate", target: "/world-map?country=USA" },
  },
  {
    id: "country-chn",
    title: "China (CHN)",
    description: "Ranked #2 Global Economy ($17.7T GDP), #11 GII",
    category: "countries",
    badge: "🇨🇳 Country",
    iconName: "MapPin",
    keywords: ["china", "chn", "beijing", "shanghai"],
    action: { type: "navigate", target: "/world-map?country=CHN" },
  },
  {
    id: "country-deu",
    title: "Germany (DEU)",
    description: "Ranked #3 Global Economy ($4.45T GDP), #5 Global Rank",
    category: "countries",
    badge: "🇩🇪 Country",
    iconName: "MapPin",
    keywords: ["germany", "deu", "berlin", "munich"],
    action: { type: "navigate", target: "/world-map?country=DEU" },
  },
  {
    id: "country-jpn",
    title: "Japan (JPN)",
    description: "Ranked #4 Global Economy ($4.21T GDP), #7 Global Rank",
    category: "countries",
    badge: "🇯🇵 Country",
    iconName: "MapPin",
    keywords: ["japan", "jpn", "tokyo", "osaka"],
    action: { type: "navigate", target: "/world-map?country=JPN" },
  },
  {
    id: "country-gbr",
    title: "United Kingdom (GBR)",
    description: "Ranked #6 Global Economy ($3.33T GDP), #8 Global Rank",
    category: "countries",
    badge: "🇬🇧 Country",
    iconName: "MapPin",
    keywords: ["united kingdom", "uk", "gbr", "britain", "london"],
    action: { type: "navigate", target: "/world-map?country=GBR" },
  },
  {
    id: "country-sgp",
    title: "Singapore (SGP)",
    description: "Ranked #1 Global Rank Overall, #1 Digital Government",
    category: "countries",
    badge: "🇸🇬 Country",
    iconName: "MapPin",
    keywords: ["singapore", "sgp"],
    action: { type: "navigate", target: "/world-map?country=SGP" },
  },
  {
    id: "country-bra",
    title: "Brazil (BRA)",
    description: "Ranked #9 Global Economy ($2.17T GDP), Latin America leader",
    category: "countries",
    badge: "🇧🇷 Country",
    iconName: "MapPin",
    keywords: ["brazil", "bra", "brasilia"],
    action: { type: "navigate", target: "/world-map?country=BRA" },
  },
  {
    id: "country-aus",
    title: "Australia (AUS)",
    description: "Ranked #6 Global Rank Overall, Oceania leader",
    category: "countries",
    badge: "🇦🇺 Country",
    iconName: "MapPin",
    keywords: ["australia", "aus", "canberra", "sydney"],
    action: { type: "navigate", target: "/world-map?country=AUS" },
  },
  {
    id: "country-fra",
    title: "France (FRA)",
    description: "Ranked #7 Global Economy ($3.05T GDP), #9 Global Rank",
    category: "countries",
    badge: "🇫🇷 Country",
    iconName: "MapPin",
    keywords: ["france", "fra", "paris"],
    action: { type: "navigate", target: "/world-map?country=FRA" },
  },
  {
    id: "country-are",
    title: "United Arab Emirates (UAE)",
    description: "Ranked #22 Global Rank, Middle East innovation hub",
    category: "countries",
    badge: "🇦🇪 Country",
    iconName: "MapPin",
    keywords: ["united arab emirates", "uae", "are", "dubai", "abu dhabi"],
    action: { type: "navigate", target: "/world-map?country=ARE" },
  },
  {
    id: "action-compare-ind-chn",
    title: "Compare India and China",
    description: "Direct side-by-side benchmark of India (IND) vs China (CHN)",
    category: "actions",
    badge: "Command",
    iconName: "ArrowLeftRight",
    keywords: ["compare india and china", "india vs china", "ind vs chn", "china"],
    action: { type: "navigate", target: "/compare?c1=IND&c2=CHN" },
  },
  {
    id: "action-explain-hdi",
    title: "Explain HDI",
    description: "Ask IndiaLens AI to analyze India's Human Development Index ranking",
    category: "ai-prompts",
    badge: "AI Command",
    iconName: "Sparkles",
    keywords: ["explain hdi", "hdi", "human development index", "health spending"],
    action: { type: "ai-prompt", target: "Explain India's Human Development Index ranking in detail." },
  },
  {
    id: "action-generate-report",
    title: "Generate Report",
    description: "Export full multi-year intelligence report for India",
    category: "actions",
    badge: "Action",
    iconName: "Download",
    keywords: ["generate report", "export report", "download report", "print", "pdf"],
    action: { type: "custom-action", target: "export-report" },
  },
];
