"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useYear } from "@/providers";
import { AIInsightCardData, getAIData } from "@/data/mock";
import {
  Brain,
  TrendingUp,
  AlertTriangle,
  Compass,
  Sparkles,
  ChevronDown,
  CheckCircle2,
  LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

const iconMap: Record<string, LucideIcon> = {
  Brain,
  TrendingUp,
  AlertTriangle,
  Compass,
  Sparkles,
};

export interface AIInsightCardsProps {
  cards?: AIInsightCardData[];
  onPromptClick?: (prompt: string) => void;
}

export function AIInsightCards({
  cards,
  onPromptClick,
}: AIInsightCardsProps) {
  const { selectedYear } = useYear();
  const displayCards = cards || getAIData(selectedYear).insightCards;
  const [expandedId, setExpandedId] = useState<string>("exec-summary");

  const toggleExpand = (id: string) => {
    setExpandedId((prev) => (prev === id ? "" : id));
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-foreground flex items-center gap-2">
            <Brain className="w-5 h-5 text-primary animate-pulse" />
            AI Intelligence Report Cards ({selectedYear})
          </h2>
          <p className="text-xs text-muted-foreground">
            Structured analysis generated by IndiaLens AI core models
          </p>
        </div>
      </div>

      <div className="space-y-3">
        {displayCards.map((card, idx) => {
          const IconComponent = iconMap[card.iconName] || Brain;
          const isExpanded = expandedId === card.id;

          return (
            <motion.div
              key={card.id}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.05 }}
              className={cn(
                "glass-card-hover rounded-2xl border transition-all overflow-hidden cursor-pointer",
                isExpanded
                  ? "border-primary/40 bg-card shadow-md"
                  : "border-border/50 bg-card/60"
              )}
              onClick={() => toggleExpand(card.id)}
            >
              {/* Card Header */}
              <div className="p-4 sm:p-5 flex items-center justify-between gap-3">
                <div className="flex items-center gap-3">
                  <div
                    className={cn(
                      "w-10 h-10 rounded-xl flex items-center justify-center border transition-all shrink-0",
                      card.badgeVariant === "primary" && "bg-primary/10 text-primary border-primary/20",
                      card.badgeVariant === "emerald" && "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
                      card.badgeVariant === "rose" && "bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20",
                      card.badgeVariant === "indigo" && "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/20",
                      card.badgeVariant === "amber" && "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20"
                    )}
                  >
                    <IconComponent className="w-5 h-5" />
                  </div>

                  <div>
                    <div className="flex items-center gap-2">
                      <h3 className="font-bold text-base text-foreground">
                        {card.title}
                      </h3>
                      <span
                        className={cn(
                          "px-2 py-0.5 rounded-full text-[10px] font-extrabold border uppercase tracking-wider",
                          card.badgeVariant === "primary" && "bg-primary/15 text-primary border-primary/30",
                          card.badgeVariant === "emerald" && "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/30",
                          card.badgeVariant === "rose" && "bg-rose-500/15 text-rose-600 dark:text-rose-400 border-rose-500/30",
                          card.badgeVariant === "indigo" && "bg-indigo-500/15 text-indigo-600 dark:text-indigo-400 border-indigo-500/30",
                          card.badgeVariant === "amber" && "bg-amber-500/15 text-amber-600 dark:text-amber-400 border-amber-500/30"
                        )}
                      >
                        {card.badge}
                      </span>
                    </div>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      {card.subtitle}
                    </p>
                  </div>
                </div>

                <button
                  className="p-1.5 rounded-lg text-muted-foreground hover:text-foreground hover:bg-secondary transition-all cursor-pointer"
                  aria-label="Toggle details"
                >
                  <ChevronDown
                    className={cn(
                      "w-4 h-4 transition-transform duration-300",
                      isExpanded && "rotate-180 text-primary"
                    )}
                  />
                </button>
              </div>

              {/* Card Collapsible Content */}
              <AnimatePresence>
                {isExpanded && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3 }}
                    className="px-4 pb-4 sm:px-5 sm:pb-5 pt-0 border-t border-border/30 space-y-3"
                  >
                    <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed pt-3">
                      {card.content}
                    </p>

                    {/* Key Highlights Bullet points */}
                    <div className="space-y-1.5 pt-1">
                      <div className="text-[11px] font-extrabold uppercase tracking-wider text-muted-foreground">
                        Key Synthesis Highlights
                      </div>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                        {card.keyPoints.map((point, pIdx) => (
                          <div
                            key={pIdx}
                            className="p-2.5 rounded-xl bg-secondary/50 border border-border/40 text-xs font-semibold text-foreground flex items-start gap-2"
                          >
                            <CheckCircle2 className="w-3.5 h-3.5 text-primary mt-0.5 shrink-0" />
                            <span>{point}</span>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Quick Ask AI button */}
                    {onPromptClick && (
                      <div className="pt-2 flex justify-end">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            onPromptClick(`Explain ${card.title} in detail for ${selectedYear}.`);
                          }}
                          className="inline-flex items-center gap-1.5 text-xs font-bold text-primary hover:underline cursor-pointer"
                        >
                          <Sparkles className="w-3.5 h-3.5" />
                          <span>Ask AI deeper details about {card.title}</span>
                        </button>
                      </div>
                    )}
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}
